// src/components/BookingSection.tsx
import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Calendar as CalendarIcon, Clock, Users, MessageCircle } from 'lucide-react';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { format } from 'date-fns';
import { supabase } from '@/lib/supabase';

interface WeeklyBooking {
  id: number;
  week_start_date: string;
  booking_count: number;
}

const MAX_CAPACITY = 50;

export default function BookingSection() {
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    email: '',
    selectedWeek: '',
    participants: '1', // Default to 1, will be updated based on package selection
    selectedPackage: 'vip', // Default to Royal VIP package
    specialRequests: '',
    oneDayDate: undefined as Date | undefined
  });
  const [availableWeeks, setAvailableWeeks] = useState<WeeklyBooking[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    fetchAvailableWeeks();
    
    // Subscribe to realtime changes
    const channel = supabase
      .channel('weekly_bookings_changes')
      .on('postgres_changes', 
        { event: '*', schema: 'public', table: 'weekly_bookings' },
        () => {
          fetchAvailableWeeks();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  const fetchAvailableWeeks = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('get-weekly-bookings');
      if (error) throw error;
      
      // Filter weeks that have available slots (less than MAX_CAPACITY bookings)
      const available = data.data.filter((week: WeeklyBooking) => week.booking_count < MAX_CAPACITY);
      setAvailableWeeks(available);
    } catch (error) {
      console.error('Error fetching available weeks:', error);
    } finally {
      setLoading(false);
    }
  };

  const getThursdayDate = (weekStartDate: string) => {
    // The weekStartDate should already be the Thursday date selected by user
    const selectedDate = new Date(weekStartDate);
    return selectedDate.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  const getAvailableSlots = (weekData: WeeklyBooking) => {
    return MAX_CAPACITY - weekData.booking_count;
  };

  // const generateBookingNumber = (bookingCount: number) => {
  //   return 'KT' + bookingCount.toString().padStart(4, '0');
  // };
  const calculateTotalPrice = (packageType: string, guests: number) => {
    const pricePerPerson = packageType === 'vip' ? 2900 : 900;
    return pricePerPerson * guests;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (formData.selectedPackage === 'vip' && !formData.selectedWeek) {
      alert('Please select a week for the Royal VIP package.');
      return;
    }

    if (formData.selectedPackage === 'oneday' && !formData.oneDayDate) {
      alert('Please select a date for the One Day package.');
      return;
    }

    setSubmitting(true);

    let bookingDateDisplay = '';
    let newBookingCount = 0;
    let remainingSlots = 0;

    try {
      if (formData.selectedPackage === 'vip') {
        // Check if enough slots are available
        const selectedWeekData = availableWeeks.find(w => w.week_start_date === formData.selectedWeek);
        if (!selectedWeekData) {
          throw new Error('Selected week data not found');
        }
        
        const availableSlots = getAvailableSlots(selectedWeekData);
        const requestedParticipants = parseInt(formData.participants);
        
        if (requestedParticipants > availableSlots) {
          alert(`Not enough slots available. Requested: ${requestedParticipants}, Available: ${availableSlots}`);
          setSubmitting(false);
          return;
        }

        // Book the slot for VIP package
        const { data, error } = await supabase.functions.invoke('book-weekly-slot', {
          body: { weekStartDate: formData.selectedWeek, participants: requestedParticipants }
        });

        if (error) throw error;
        if (!data.success) throw new Error(data.message);

        newBookingCount = data.newCount;
        bookingDateDisplay = getThursdayDate(formData.selectedWeek);
        remainingSlots = MAX_CAPACITY - newBookingCount;
      } else if (formData.selectedPackage === 'oneday' && formData.oneDayDate) {
        // For one-day package, no slot booking needed on backend for now
        // Just format the date for display
        bookingDateDisplay = format(formData.oneDayDate, 'EEEE dd, MMMM yyyy'); // e.g., 'Monday 25, October 2024'
        newBookingCount = 0; // Not applicable for one-day
        remainingSlots = 0; // Not applicable for one-day
      }

      const totalPrice = calculateTotalPrice(formData.selectedPackage, parseInt(formData.participants));
      const packageName = formData.selectedPackage === 'vip' ? 'King Tut Royal VIP (5 Days / 4 Nights)' : 'King Tut VIP One Day';

      const message = `
🎁 *${packageName}*

📋 *Booking Details:*
${formData.selectedPackage === 'vip' ? `🎫 Booking number: ${newBookingCount}` : ''}
👤 Name: ${formData.name}
📱 Phone: ${formData.phone}
📧 Email: ${formData.email}
👥 Guests: ${formData.participants}
📅 Booking Date: ${bookingDateDisplay}
€ Total Price: €${totalPrice.toLocaleString()}
${formData.selectedPackage === 'vip' ? `🎟️ Remaining Slots: ${remainingSlots}` : ''}
${formData.specialRequests ? `📝 Special Requests: ${formData.specialRequests}` : ''}
`;

      const whatsappUrl = `https://wa.me/+971585923054?text=${encodeURIComponent(message)}`;
      window.open(whatsappUrl, '_blank');

      // Refresh available weeks (only relevant for VIP package)
      if (formData.selectedPackage === 'vip') {
        await fetchAvailableWeeks();
      }

      // Reset form
      setFormData({ name: '', phone: '', email: '', selectedWeek: '', participants: '1', selectedPackage: 'vip', specialRequests: '', oneDayDate: undefined });
    } catch (error) {
      console.error('Booking error:', error);
      alert('Booking failed. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <section id="booking" className="py-20 bg-black">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-white mb-4">Book Your Royal Experience</h2>
          <p className="text-xl text-amber-400 max-w-2xl mx-auto">
            Limited to 50 bookings per week - Secure your spot now!
          </p>
        </div>

        <Card className="bg-gray-900 border border-amber-400 shadow-xl">
          <CardHeader className="text-center border-b border-amber-400/20">
            <CardTitle className="flex items-center justify-center gap-2 text-2xl text-white">
              Select Your Package
            </CardTitle>
            <CardDescription className="text-gray-300">Choose your preferred package and date</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6 p-8">
            {/* Package Selection */}
            <div className="space-y-4 mb-8">
              <Label className="text-white text-lg">Select Package *</Label>
              <div className="grid md:grid-cols-2 gap-4">
                <div 
                  className={`cursor-pointer rounded-lg p-4 border-2 transition-all ${
                    formData.selectedPackage === 'vip' 
                      ? 'bg-amber-400/20 border-amber-400' 
                      : 'bg-gray-800 border-gray-600 hover:border-amber-400/50'
                  }`}
                  onClick={() => setFormData(prev => ({...prev, selectedPackage: 'vip'}))}
                >
                  <h3 className="text-lg font-semibold text-amber-400 mb-2">King Tut Royal VIP</h3>
                  <p className="text-white text-2xl font-bold">€2,900</p>
                  <p className="text-gray-300 text-sm">5 Days / 4 Nights</p>
                  <p className="text-gray-300 text-sm">per person</p>
                </div>
                <div 
                  className={`cursor-pointer rounded-lg p-4 border-2 transition-all ${
                    formData.selectedPackage === 'oneday' 
                      ? 'bg-amber-400/20 border-amber-400' 
                      : 'bg-gray-800 border-gray-600 hover:border-amber-400/50'
                  }`}
                  onClick={() => setFormData(prev => ({...prev, selectedPackage: 'oneday', participants: '4'}))}
                >
                  <h3 className="text-lg font-semibold text-white mb-2">King Tut VIP One Day</h3>
                  <p className="text-white text-2xl font-bold">€900</p>
                  <p className="text-gray-300 text-sm">Full Day Experience</p>
                  <p className="text-gray-300 text-sm">per person</p>
                </div>
              </div>
            </div>
            
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="name" className="text-white">Full Name *</Label>
                  <Input
                    id="name"
                    type="text"
                    value={formData.name}
                    onChange={(e) => setFormData(prev => ({...prev, name: e.target.value}))}
                    required
                    className="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="email" className="text-white">Email *</Label>
                  <Input
                    id="email"
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData(prev => ({...prev, email: e.target.value}))}
                    required
                    className="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="phone" className="text-white">Phone</Label>
                  <Input
                    id="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={(e) => setFormData(prev => ({...prev, phone: e.target.value}))}
                    className="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="participants" className="text-white">Number of Guests</Label>
                  <Select
                    value={formData.participants}
                    onValueChange={(value) => setFormData(prev => ({
                      ...prev,
                      participants: value
                    }))}
                  >
                    <SelectTrigger className="h-12 bg-gray-800 border-gray-600 text-white">
                      <SelectValue placeholder="Select guests" />
                    </SelectTrigger>
                    <SelectContent className="bg-gray-800 border-gray-600">
                      {formData.selectedPackage === 'oneday' ? (
                        <>
                          <SelectItem value="4" className="text-white hover:bg-gray-700">4 Guests</SelectItem>
                          <SelectItem value="5" className="text-white hover:bg-gray-700">5 Guests</SelectItem>
                          <SelectItem value="6" className="text-white hover:bg-gray-700">6 Guests</SelectItem>
                        </>
                      ) : (
                        <>
                          <SelectItem value="1" className="text-white hover:bg-gray-700">1 Guest</SelectItem>
                          <SelectItem value="2" className="text-white hover:bg-gray-700">2 Guests</SelectItem>
                          <SelectItem value="3" className="text-white hover:bg-gray-700">3 Guests</SelectItem>
                          <SelectItem value="4" className="text-white hover:bg-gray-700">4 Guests</SelectItem>
                          <SelectItem value="5" className="text-white hover:bg-gray-700">5 Guests</SelectItem>
                          <SelectItem value="6" className="text-white hover:bg-gray-700">6 Guests</SelectItem>
                        </>
                      )}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="date" className="text-white">Select Date *</Label>
                {formData.selectedPackage === 'oneday' ? (
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant={"outline"}
                        className={`w-full justify-start text-left font-normal h-12 bg-gray-800 border-gray-600 text-white ${!formData.oneDayDate && "text-muted-foreground"}`}
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {formData.oneDayDate ? format(formData.oneDayDate, "PPP") : <span>Pick a date</span>}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0 bg-gray-800 border-gray-600 text-white">
                      <Calendar
                        mode="single"
                        selected={formData.oneDayDate}
                        onSelect={(date) => setFormData(prev => ({ ...prev, oneDayDate: date }))}
                        initialFocus
                        month={new Date(new Date().getFullYear(), 10)} // Set initial month to November (month index 10)
                      />
                    </PopoverContent>
                  </Popover>
                ) : (
                  <Select
                    value={formData.selectedWeek}
                    onValueChange={(value) => setFormData(prev => ({...prev, selectedWeek: value}))}
                    required
                  >
                    <SelectTrigger className="h-12 bg-gray-800 border-gray-600 text-white">
                      <SelectValue placeholder={loading ? "Loading dates..." : "Choose your Thursday"} />
                    </SelectTrigger>
                    <SelectContent className="bg-gray-800 border-gray-600">
                      {availableWeeks.map((week) => (
                        <SelectItem key={week.id} value={week.week_start_date} className="text-white hover:bg-gray-700">
                          <div className="flex items-center justify-between w-full">
                            <span>{getThursdayDate(week.week_start_date)}</span>
                            <span className="ml-4 text-sm text-green-400">
                              {getAvailableSlots(week)} slots available
                            </span>
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="requests" className="text-white">Special requests</Label>
                <textarea
                  id="requests"
                  rows={4}
                  value={formData.specialRequests}
                  onChange={(e) => setFormData(prev => ({ ...prev, specialRequests: e.target.value }))}
                  className="w-full p-3 bg-gray-800 border border-gray-600 rounded-md text-white focus:border-amber-400 focus:outline-none"
                  placeholder="Any special requests or requirements..."
                />
              </div>

              <div className="mt-8 text-center">
                <p className="text-primary text-2xl font-bold">Total Price: €{calculateTotalPrice(formData.selectedPackage, parseInt(formData.participants)).toLocaleString()}</p>
              </div>

              <Button
                type="submit"
                disabled={!formData.name || (formData.selectedPackage === 'vip' && !formData.selectedWeek) || (formData.selectedPackage === 'oneday' && !formData.oneDayDate) || submitting}
                className="w-full h-14 text-lg bg-gradient-to-r from-amber-400 to-amber-600 text-black hover:from-amber-500 hover:to-amber-700 font-semibold"
              >
                <MessageCircle className="mr-2 h-5 w-5" />
                {submitting ? 'Processing...' : 'Secure Your Booking'}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}

// src/components/sections/BookingSection.vue
<template>
  <section id="booking" class="py-10 bg-light-yellow font-sans">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center mb-12">
        <h2 class="text-2xl sm:text-2xl font-bold text-foreground mb-4">Book Your Royal Experience</h2>
        <p class="text-md sm:text-md text-brownish font-bold max-w-2xl mx-auto">
          Limited to 50 bookings per week - Secure your spot now!
        </p>
      </div>

      <div class="bg-card border border-primary/20 shadow-xl rounded-lg">
        <div class="text-center border-b border-border p-6">
          <h3 class="flex items-center justify-center gap-2 text-xl sm:text-2xl text-foreground font-semibold">
            Booking Details
          </h3>
          <p class="text-sm sm:text-base text-muted-foreground mt-2">Choose your preferred date</p>
        </div>
        <div class="space-y-6 p-8">
          <!-- Package Selection -->
          <div class="space-y-4 mb-8">
            <Label class="text-foreground text-base sm:text-lg">Your Package *</Label>
            <div class="grid md:grid-cols-1 gap-4">
              <template v-for="(pkg, index) in packagesData" :key="pkg.key || index">
                <div 
                  class="cursor-pointer rounded-lg p-4 border-2 transition-all bg-primary/20 border-primary"
                >
                  <h3 class="text-base sm:text-lg font-semibold text-primary mb-2">{{ pkg.title }}</h3>
                  <p class="text-lg sm:text-2xl font-bold text-foreground">{{ pkg.price }}</p>
                  <p v-if="pkg.details?.itinerary" class="text-xs sm:text-sm text-muted-foreground">{{ pkg.details.itinerary.length }} Days / {{ pkg.details.itinerary.length ? pkg.details.itinerary.length - 1 : 0 }} Nights</p>
                  <p v-else class="text-xs sm:text-sm text-muted-foreground">Full Day Experience</p>
                  <p v-if="pkg.details?.per_person" class="text-xs sm:text-sm text-muted-foreground">per person</p>
                </div>
              </template>
            </div>
          </div>
          
          <form @submit.prevent="handleSubmit" class="space-y-6">
            <div class="grid md:grid-cols-2 gap-6">
              <div class="space-y-2">
                <Label for="name" class="text-foreground">Full Name *</Label>
                <Input
                  id="name"
                  v-model="formData.name"
                  type="text"
                  required
                  class="h-12 bg-input border-border text-foreground focus:border-primary"
                />
              </div>
              
              <div class="space-y-2">
                <Label for="email" class="text-foreground">Email *</Label>
                <Input
                  id="email"
                  v-model="formData.email"
                  type="email"
                  required
                  class="h-12 bg-input border-border text-foreground focus:border-primary"
                />
              </div>
            </div>

            <div class="grid md:grid-cols-2 gap-6">
              <div class="space-y-2">
                <Label for="phone" class="text-foreground">Phone *</Label>
                <PhoneInput
                  id="phone"
                  v-model="formData.phone"
                  mode="international"
                  :inputOptions="{ placeholder: 'Enter your phone number' }"
                  class="h-12 bg-input border-border text-foreground focus:border-primary"
                />
                <p class="text-primary text-sm mt-1">Please enter a valid phone number, including country code.</p>
              </div>

              <div class="space-y-2">
                <Label for="participants" class="text-foreground">Number of Guests *</Label>
                <select
                  v-model="formData.participants"
                  class="h-12 w-full bg-input border border-border text-foreground rounded-md px-3 focus:border-primary focus:outline-none"
                  style="-webkit-appearance: none; -moz-appearance: none; appearance: none; padding-right: 32px;"
                >
                  <option value="1">1 Guest</option>
                  <option value="2">2 Guests</option>
                  <option value="3">3 Guests</option>
                  <option value="4">4 Guests</option>
                  <option value="5">5 Guests</option>
                  <option value="6">6 Guests</option>
                </select>
              </div>
            </div>

            <div class="space-y-2">
              <Label class="text-foreground">Select Date *</Label>
              <div>
                <select
                  v-model="formData.selectedWeek"
                  required
                  class="h-12 w-full bg-input border border-border text-foreground rounded-md px-3 focus:border-primary focus:outline-none"
                >
                  <option value="">{{ loading ? "Loading dates..." : "Choose your Thursday" }}</option>
                  <template v-for="week in availableWeeks" :key="week.id">
                    <template v-if="new Date(week.week_start_date) >= new Date()">
                      <option 
                        :value="week.week_start_date"
                        :class="{
                          'text-green-500': getAvailableSlots(week) > 25,
                          'text-yellow-500': getAvailableSlots(week) > 12 && getAvailableSlots(week) <= 25,
                          'text-orange-500': getAvailableSlots(week) <= 12
                        }"
                      >
                        {{ getThursdayDate(week.week_start_date) }} - {{ getAvailableSlots(week) }} slots available
                      </option>
                    </template>
                  </template>
                </select>
              </div>
            </div>

            <div class="space-y-2">
              <Label for="requests" class="text-foreground">Special requests</Label>
              <textarea
                id="requests"
                v-model="formData.specialRequests"
                rows="4"
                class="w-full p-3 bg-input border border-border rounded-md text-foreground focus:border-primary focus:outline-none"
                placeholder="Any special requests or requirements..."
              />
            </div>

            <div class="mt-8 text-center">
              <p class="text-primary text-xl font-bold">
                Price / person: €{{ totalPrice.toLocaleString() }}
              </p>
            </div>

            <Button
              type="submit"
              class="w-full h-14 text-lg bg-green-600 hover:bg-green-700 text-white font-semibold disabled:opacity-90"
            >
               <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893A11.821 11.821 0 0020.413 3.106"/>
              </svg>
              <span class="mx-3">
                {{ submitting ? 'Processing...' : 'Send' }}
              </span>
            </Button>
          </form>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted, computed, watch, defineAsyncComponent } from 'vue'
import { KING_TUT_ROYAL_VIP } from '@/constants/packageIds';
import { format } from 'date-fns'
import { MessageCircle } from 'lucide-vue-next'
import { supabase } from '@/lib/supabase'
import { useRoute } from 'vue-router';
import { useToast } from '@/composables/useToast';
import type { PackageData } from '@/types';

const PhoneInput = defineAsyncComponent(() => import('@/components/ui/PhoneInput.vue'))

const Button = defineAsyncComponent(() => import('@/components/ui/button.vue'))
const Input = defineAsyncComponent(() => import('@/components/ui/input.vue'))
const Label = defineAsyncComponent(() => import('@/components/ui/label.vue'))

const props = defineProps({
  preselectedPackageId: {
    type: String,
    default: KING_TUT_ROYAL_VIP
  },
  preselectedDate: {
    type: String,
    default: null
  },
  preselectedWeek: {
    type: String,
    default: null
  }
});

const emit = defineEmits(['loaded']);

const PACKAGE_PRICING = ref<{[key: string]: number}>({});

onMounted(async () => {
  try {
    // Fetch only the Royal VIP package (limit 1)
    const { data, error } = await supabase
      .from('packages_view')
      .select('package, sort_rank')
      .eq('package->>slug', KING_TUT_ROYAL_VIP)
      .limit(1)
      .single();

    if (error) {
      console.error('Error fetching package:', error);
      return;
    }

    // Populate packagesData with the single package
    packagesData.value = data ? [data.package] : [];

    // Build pricing map keyed by slug from priceAmountCents (fallback to booking.price_amount_cents)
    PACKAGE_PRICING.value = {};
    packagesData.value.forEach((pkg: any) => {
      const cents = pkg?.priceAmountCents ?? pkg?.details?.booking?.price_amount_cents ?? 0;
      if (pkg?.slug && cents) {
        PACKAGE_PRICING.value[pkg.slug] = cents / 100;
      }
    });

    // Set default selected package
    formData.selectedPackage = KING_TUT_ROYAL_VIP;
  } catch (error) {
    console.error('Error in onMounted:', error);
  }
  
  emit('loaded');
  
  if (props.preselectedWeek) {
    formData.selectedWeek = props.preselectedWeek;
  }

  // Fetch available weeks for booking
  await fetchAvailableWeeks()
  
  // Subscribe to real-time updates for weekly bookings
  channel = supabase
    .channel('weekly_bookings_changes')
    .on('postgres_changes', 
      { event: '*', schema: 'public', table: 'weekly_bookings' },
      () => {
        fetchAvailableWeeks()
      }
    )
    .subscribe()
});

interface WeeklyBooking {
  id: number
  week_start_date: string
  booking_count: number
}

const MAX_CAPACITY = 50

// Reactive form data - simplified structure
const formData = reactive({
  name: '',
  phone: '',
  email: '',
  selectedWeek: '',
  participants: '1',
  selectedPackage: KING_TUT_ROYAL_VIP, // Always set to Royal VIP
  specialRequests: ''
})

// State
const availableWeeks = ref<WeeklyBooking[]>([])
const loading = ref(true)
const submitting = ref(false)
let channel: any = null

// Watch for phone input changes to sanitize and ensure single leading plus is preserved
watch(() => formData.phone, (newValue) => {
  if (newValue) {
    let cleaned = newValue.replace(/[^0-9+]/g, '')
    const hasPlus = cleaned.includes('+')
    // Remove all plus signs then, if any were present, prefix a single plus
    const numeric = cleaned.replace(/\+/g, '')
    formData.phone = hasPlus ? `+${numeric}` : numeric
  }
})

// Computed for form validation
const isFormValid = computed(() => {
  const hasName = formData.name && formData.name.trim().length > 0
  const hasEmail = formData.email && formData.email.trim().length > 0
  const hasSelectedWeek = formData.selectedWeek && formData.selectedWeek.length > 0
  
  return hasName && hasEmail && hasSelectedWeek
})

// Computed for reactive total price calculation
const totalPrice = computed(() => {
  const pricing = PACKAGE_PRICING.value || {};
  const selectedSlug = formData.selectedPackage || KING_TUT_ROYAL_VIP;
  const pricePerPerson = pricing[selectedSlug] || 0;
  const numGuests = parseInt(formData.participants) || 1;
  return pricePerPerson * numGuests;
});

// Methods
const fetchAvailableWeeks = async () => {
  try {
    const { data, error } = await supabase.functions.invoke('get-weekly-bookings')
    if (error) throw error
    
    // Filter weeks that have available slots (less than MAX_CAPACITY bookings)
    const available = data.data.filter((week: WeeklyBooking) => week.booking_count < MAX_CAPACITY)
    availableWeeks.value = available
  } catch (error) {
    console.error('Error fetching available weeks:', error);
    availableWeeks.value = []; // Provide default empty array to prevent rendering issues
  } finally {
    loading.value = false
  }
}

const getThursdayDate = (weekStartDate: string) => {
  const selectedDate = new Date(weekStartDate)
  return format(selectedDate, 'EEEE dd, MMMM yyyy')
}

const getAvailableSlots = (weekData: WeeklyBooking) => {
  return MAX_CAPACITY - weekData.booking_count
}

const selectPackage = (packageId: string) => {
  formData.selectedPackage = KING_TUT_ROYAL_VIP; // Always ensure Royal VIP is selected
  formData.participants = '1'; // Default to 1 guest for Royal VIP
};

// Add missing packagesData ref
const packagesData = ref<PackageData[]>([]);

// Fetch packages data in the existing onMounted hook
// This code will be merged with the existing onMounted

const handleSubmit = async () => {
  if (!formData.name.trim()) {
    alert('Please enter your full name.')
    return
  }

  if (!formData.phone.trim()) {
    alert('Please enter your phone number.')
    return
  }

  // Require international code (must start with + and country code)
  const phoneIntlRegex = /^\+\d{6,15}$/
  if (!phoneIntlRegex.test(formData.phone.trim())) {
    alert('Please provide your phone number with the international country code (e.g. +971589123456) and do not remove the + sign.')
    return
  }

  if (!formData.participants || parseInt(formData.participants) <= 0) {
    alert('Please enter the number of guests.')
    return
  }

  if (!formData.selectedWeek) {
    alert('Please select a week for the Royal VIP package.')
    return
  }

  submitting.value = true

  let bookingDateDisplay = ''
  let newBookingCount = 0
  let remainingSlots = 0

  try {
    // Check if enough slots are available
    const selectedWeekData = availableWeeks.value.find(w => w.week_start_date === formData.selectedWeek)
    if (!selectedWeekData) {
      throw new Error('Selected week data not found')
    }
    
    const availableSlots = getAvailableSlots(selectedWeekData)
    const requestedParticipants = parseInt(formData.participants)
    
    if (requestedParticipants > availableSlots) {
      alert(`Not enough slots available. Requested: ${requestedParticipants}, Available: ${availableSlots}`)
      submitting.value = false
      return
    }

    // Book the slot for VIP package
    const { data, error } = await supabase.functions.invoke('book-weekly-slot', {
      body: { weekStartDate: formData.selectedWeek, participants: requestedParticipants }
    })

    if (error) throw error
    if (!data.success) throw new Error(data.message)

    newBookingCount = data.newCount
    bookingDateDisplay = getThursdayDate(formData.selectedWeek)
    remainingSlots = MAX_CAPACITY - newBookingCount

    const totalPriceValue = totalPrice.value
    
    // Get the actual package name from packagesData
    const packageName = 'King Tut Royal VIP' // Hardcoded since we only have one package

    const message = `
📋 *Booking Details:*
${packageName}
👤 Name: ${formData.name}
📱 Phone: ${formData.phone}
📧 Email: ${formData.email}
👥 Guests: ${formData.participants}
📅 Booking Date: ${bookingDateDisplay}
€ Total Price: €${totalPriceValue.toLocaleString()}
🎟️ Remaining Slots: ${remainingSlots}
${formData.specialRequests ? `📝 Special Requests: ${formData.specialRequests}` : ''}
`

    const whatsappUrl = `https://api.whatsapp.com/send?phone=201270389777&text=${encodeURIComponent(message)}`
    window.open(whatsappUrl, '_blank')

    // Refresh available weeks
    await fetchAvailableWeeks()

    // Reset form but keep Royal VIP selected
    Object.assign(formData, {
      name: '',
      phone: '',
      email: '',
      selectedWeek: '',
      participants: '1',
      selectedPackage: KING_TUT_ROYAL_VIP, // Always keep Royal VIP selected
      specialRequests: ''
    })
  } catch (error) {
    console.error('Booking error:', error)
    alert('Booking failed. Please try again.')
  } finally {
    submitting.value = false
  }
}



onUnmounted(() => {
  if (channel) {
    supabase.removeChannel(channel)
  }
})
</script>

<style scoped>
/* Font normalization for the entire component */
* {
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
</style>
