// src/components/AppLayout.vue
<template>
  <div class="min-h-screen bg-black text-white">
    <Navigation />
    <main>
      <section id="home">
        <HeroSection />
      </section>
      <VideoSection />
      <section id="packages">
        <PackagesSection />
      </section>
      <MediaSliderSection />
      <WhyChooseSection />
      <BookingSection />
    </main>
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Navigation from './Navigation.vue'
import HeroSection from './HeroSection.vue'
import MediaSliderSection from './MediaSliderSection.vue'
import PackagesSection from './PackagesSection.vue'
import VideoSection from './sections/VideoSection.vue'
import WhyChooseSection from './WhyChooseSection.vue'
import BookingSection from './BookingSection.vue'
import Footer from './Footer.vue'
</script>

// src/components/AppLayout.tsx
import React from 'react';
import Navigation from './Navigation';
import HeroSection from './HeroSection';
import MediaSliderSection from './MediaSliderSection';
import PackagesSection from './PackagesSection';
import WhyChooseSection from './WhyChooseSection';
import BookingSection from './BookingSection';
import Footer from './Footer';
const AppLayout: React.FC = () => {
  return (
    <div className="min-h-screen bg-black text-white">
      <Navigation />
      <main>
        <section id="home">
          <HeroSection />
        </section>
        <MediaSliderSection />
        <section id="packages">
          <PackagesSection />
        </section>
        <WhyChooseSection />
        <BookingSection />
      </main>
      <Footer />
    </div>
  );
};
export default AppLayout;
