// src/components/BookingSection.tsx
import { useState, useEffect } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Calendar as CalendarIcon, Clock, Users, MessageCircle } from 'lucide-react';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { format } from 'date-fns';
import { supabase } from '@/lib/supabase';

interface WeeklyBooking {
  id: number;
  week_start_date: string;
  booking_count: number;
}

const MAX_CAPACITY = 50;

export default function BookingSection() {
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    email: '',
    selectedWeek: '',
    participants: '1', // Default to 1, will be updated based on package selection
    selectedPackage: 'vip', // Default to Royal VIP package
    specialRequests: '',
    oneDayDate: undefined as Date | undefined
  });
  const [availableWeeks, setAvailableWeeks] = useState<WeeklyBooking[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    fetchAvailableWeeks();
    
    // Subscribe to realtime changes
    const channel = supabase
      .channel('weekly_bookings_changes')
      .on('postgres_changes', 
        { event: '*', schema: 'public', table: 'weekly_bookings' },
        () => {
          fetchAvailableWeeks();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  const fetchAvailableWeeks = async () => {
    try {
      const { data, error } = await supabase.functions.invoke('get-weekly-bookings');
      if (error) throw error;
      
      // Filter weeks that have available slots (less than MAX_CAPACITY bookings)
      const available = data.data.filter((week: WeeklyBooking) => week.booking_count < MAX_CAPACITY);
      setAvailableWeeks(available);
    } catch (error) {
      console.error('Error fetching available weeks:', error);
    } finally {
      setLoading(false);
    }
  };

  const getThursdayDate = (weekStartDate: string) => {
    // The weekStartDate should already be the Thursday date selected by user
    const selectedDate = new Date(weekStartDate);
    return selectedDate.toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
  };

  const getAvailableSlots = (weekData: WeeklyBooking) => {
    return MAX_CAPACITY - weekData.booking_count;
  };

  // const generateBookingNumber = (bookingCount: number) => {
  //   return 'KT' + bookingCount.toString().padStart(4, '0');
  // };
  const calculateTotalPrice = (packageType: string, guests: number) => {
    const pricePerPerson = packageType === 'vip' ? 2900 : 900;
    return pricePerPerson * guests;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (formData.selectedPackage === 'vip' && !formData.selectedWeek) {
      alert('Please select a week for the Royal VIP package.');
      return;
    }

    if (formData.selectedPackage === 'oneday' && !formData.oneDayDate) {
      alert('Please select a date for the One Day package.');
      return;
    }

    setSubmitting(true);

    let bookingDateDisplay = '';
    let newBookingCount = 0;
    let remainingSlots = 0;

    try {
      if (formData.selectedPackage === 'vip') {
        // Check if enough slots are available
        const selectedWeekData = availableWeeks.find(w => w.week_start_date === formData.selectedWeek);
        if (!selectedWeekData) {
          throw new Error('Selected week data not found');
        }
        
        const availableSlots = getAvailableSlots(selectedWeekData);
        const requestedParticipants = parseInt(formData.participants);
        
        if (requestedParticipants > availableSlots) {
          alert(`Not enough slots available. Requested: ${requestedParticipants}, Available: ${availableSlots}`);
          setSubmitting(false);
          return;
        }

        // Book the slot for VIP package
        const { data, error } = await supabase.functions.invoke('book-weekly-slot', {
          body: { weekStartDate: formData.selectedWeek, participants: requestedParticipants }
        });

        if (error) throw error;
        if (!data.success) throw new Error(data.message);

        newBookingCount = data.newCount;
        bookingDateDisplay = getThursdayDate(formData.selectedWeek);
        remainingSlots = MAX_CAPACITY - newBookingCount;
      } else if (formData.selectedPackage === 'oneday' && formData.oneDayDate) {
        // For one-day package, no slot booking needed on backend for now
        // Just format the date for display
        bookingDateDisplay = format(formData.oneDayDate, 'EEEE dd, MMMM yyyy'); // e.g., 'Monday 25, October 2024'
        newBookingCount = 0; // Not applicable for one-day
        remainingSlots = 0; // Not applicable for one-day
      }

      const totalPrice = calculateTotalPrice(formData.selectedPackage, parseInt(formData.participants));
      const packageName = formData.selectedPackage === 'vip' ? 'King Tut Royal VIP (5 Days / 4 Nights)' : 'King Tut VIP One Day';

      const message = `
🎁 *${packageName}*

📋 *Booking Details:*
${formData.selectedPackage === 'vip' ? `🎫 Booking number: ${newBookingCount}` : ''}
👤 Name: ${formData.name}
📱 Phone: ${formData.phone}
📧 Email: ${formData.email}
👥 Guests: ${formData.participants}
📅 Booking Date: ${bookingDateDisplay}
€ Total Price: €${totalPrice.toLocaleString()}
${formData.selectedPackage === 'vip' ? `🎟️ Remaining Slots: ${remainingSlots}` : ''}
${formData.specialRequests ? `📝 Special Requests: ${formData.specialRequests}` : ''}
`;

      const whatsappUrl = `https://wa.me/+971585923054?text=${encodeURIComponent(message)}`;
      window.open(whatsappUrl, '_blank');

      // Refresh available weeks (only relevant for VIP package)
      if (formData.selectedPackage === 'vip') {
        await fetchAvailableWeeks();
      }

      // Reset form
      setFormData({ name: '', phone: '', email: '', selectedWeek: '', participants: '1', selectedPackage: 'vip', specialRequests: '', oneDayDate: undefined });
    } catch (error) {
      console.error('Booking error:', error);
      alert('Booking failed. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <section id="booking" className="py-20 bg-black">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-4xl font-bold text-white mb-4">Book Your Royal Experience</h2>
          <p className="text-xl text-amber-400 max-w-2xl mx-auto">
            Limited to 50 bookings per week - Secure your spot now!
          </p>
        </div>

        <Card className="bg-gray-900 border border-amber-400 shadow-xl">
          <CardHeader className="text-center border-b border-amber-400/20">
            <CardTitle className="flex items-center justify-center gap-2 text-2xl text-white">
              Select Your Package
            </CardTitle>
            <CardDescription className="text-gray-300">Choose your preferred package and date</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6 p-8">
            {/* Package Selection */}
            <div className="space-y-4 mb-8">
              <Label className="text-white text-lg">Select Package *</Label>
              <div className="grid md:grid-cols-2 gap-4">
                <div 
                  className={`cursor-pointer rounded-lg p-4 border-2 transition-all ${
                    formData.selectedPackage === 'vip' 
                      ? 'bg-amber-400/20 border-amber-400' 
                      : 'bg-gray-800 border-gray-600 hover:border-amber-400/50'
                  }`}
                  onClick={() => setFormData(prev => ({...prev, selectedPackage: 'vip'}))}
                >
                  <h3 className="text-lg font-semibold text-amber-400 mb-2">King Tut Royal VIP</h3>
                  <p className="text-white text-2xl font-bold">€2,900</p>
                  <p className="text-gray-300 text-sm">5 Days / 4 Nights</p>
                  <p className="text-gray-300 text-sm">per person</p>
                </div>
                <div 
                  className={`cursor-pointer rounded-lg p-4 border-2 transition-all ${
                    formData.selectedPackage === 'oneday' 
                      ? 'bg-amber-400/20 border-amber-400' 
                      : 'bg-gray-800 border-gray-600 hover:border-amber-400/50'
                  }`}
                  onClick={() => setFormData(prev => ({...prev, selectedPackage: 'oneday', participants: '4'}))}
                >
                  <h3 className="text-lg font-semibold text-white mb-2">King Tut VIP One Day</h3>
                  <p className="text-white text-2xl font-bold">€900</p>
                  <p className="text-gray-300 text-sm">Full Day Experience</p>
                  <p className="text-gray-300 text-sm">per person</p>
                </div>
              </div>
            </div>
            
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="name" className="text-white">Full Name *</Label>
                  <Input
                    id="name"
                    type="text"
                    value={formData.name}
                    onChange={(e) => setFormData(prev => ({...prev, name: e.target.value}))}
                    required
                    className="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                  />
                </div>
                
                <div className="space-y-2">
                  <Label htmlFor="email" className="text-white">Email *</Label>
                  <Input
                    id="email"
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData(prev => ({...prev, email: e.target.value}))}
                    required
                    className="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                  />
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <Label htmlFor="phone" className="text-white">Phone</Label>
                  <Input
                    id="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={(e) => setFormData(prev => ({...prev, phone: e.target.value}))}
                    className="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="participants" className="text-white">Number of Guests</Label>
                  <Select
                    value={formData.participants}
                    onValueChange={(value) => setFormData(prev => ({
                      ...prev,
                      participants: value
                    }))}
                  >
                    <SelectTrigger className="h-12 bg-gray-800 border-gray-600 text-white">
                      <SelectValue placeholder="Select guests" />
                    </SelectTrigger>
                    <SelectContent className="bg-gray-800 border-gray-600">
                      {formData.selectedPackage === 'oneday' ? (
                        <>
                          <SelectItem value="4" className="text-white hover:bg-gray-700">4 Guests</SelectItem>
                          <SelectItem value="5" className="text-white hover:bg-gray-700">5 Guests</SelectItem>
                          <SelectItem value="6" className="text-white hover:bg-gray-700">6 Guests</SelectItem>
                        </>
                      ) : (
                        <>
                          <SelectItem value="1" className="text-white hover:bg-gray-700">1 Guest</SelectItem>
                          <SelectItem value="2" className="text-white hover:bg-gray-700">2 Guests</SelectItem>
                          <SelectItem value="3" className="text-white hover:bg-gray-700">3 Guests</SelectItem>
                          <SelectItem value="4" className="text-white hover:bg-gray-700">4 Guests</SelectItem>
                          <SelectItem value="5" className="text-white hover:bg-gray-700">5 Guests</SelectItem>
                          <SelectItem value="6" className="text-white hover:bg-gray-700">6 Guests</SelectItem>
                        </>
                      )}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="date" className="text-white">Select Date *</Label>
                {formData.selectedPackage === 'oneday' ? (
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant={"outline"}
                        className={`w-full justify-start text-left font-normal h-12 bg-gray-800 border-gray-600 text-white ${!formData.oneDayDate && "text-muted-foreground"}`}
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {formData.oneDayDate ? format(formData.oneDayDate, "PPP") : <span>Pick a date</span>}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0 bg-gray-800 border-gray-600 text-white">
                      <Calendar
                        mode="single"
                        selected={formData.oneDayDate}
                        onSelect={(date) => setFormData(prev => ({ ...prev, oneDayDate: date }))}
                        initialFocus
                        month={new Date(new Date().getFullYear(), 10)} // Set initial month to November (month index 10)
                      />
                    </PopoverContent>
                  </Popover>
                ) : (
                  <Select
                    value={formData.selectedWeek}
                    onValueChange={(value) => setFormData(prev => ({...prev, selectedWeek: value}))}
                    required
                  >
                    <SelectTrigger className="h-12 bg-gray-800 border-gray-600 text-white">
                      <SelectValue placeholder={loading ? "Loading dates..." : "Choose your Thursday"} />
                    </SelectTrigger>
                    <SelectContent className="bg-gray-800 border-gray-600">
                      {availableWeeks.map((week) => (
                        <SelectItem key={week.id} value={week.week_start_date} className="text-white hover:bg-gray-700">
                          <div className="flex items-center justify-between w-full">
                            <span>{getThursdayDate(week.week_start_date)}</span>
                            <span className="ml-4 text-sm text-green-400">
                              {getAvailableSlots(week)} slots available
                            </span>
                          </div>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="requests" className="text-white">Special requests</Label>
                <textarea
                  id="requests"
                  rows={4}
                  value={formData.specialRequests}
                  onChange={(e) => setFormData(prev => ({ ...prev, specialRequests: e.target.value }))}
                  className="w-full p-3 bg-gray-800 border border-gray-600 rounded-md text-white focus:border-amber-400 focus:outline-none"
                  placeholder="Any special requests or requirements..."
                />
              </div>

              <div className="mt-8 text-center">
                <p className="text-primary text-2xl font-bold">Total Price: €{calculateTotalPrice(formData.selectedPackage, parseInt(formData.participants)).toLocaleString()}</p>
              </div>

              <Button
                type="submit"
                disabled={!formData.name || (formData.selectedPackage === 'vip' && !formData.selectedWeek) || (formData.selectedPackage === 'oneday' && !formData.oneDayDate) || submitting}
                className="w-full h-14 text-lg bg-gradient-to-r from-amber-400 to-amber-600 text-black hover:from-amber-500 hover:to-amber-700 font-semibold"
              >
                <MessageCircle className="mr-2 h-5 w-5" />
                {submitting ? 'Processing...' : 'Secure Your Booking'}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </section>
  );
}

// src/components/BookingSection.vue
<template>
  <section id="booking" class="py-20 bg-black">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="text-center mb-12">
        <h2 class="text-4xl font-bold text-white mb-4">Book Your Royal Experience</h2>
        <p class="text-xl text-amber-400 max-w-2xl mx-auto">
          Limited to 50 bookings per week - Secure your spot now!
        </p>
      </div>

      <Card class="bg-gray-900 border border-amber-400 shadow-xl">
        <CardHeader class="text-center border-b border-amber-400/20">
          <CardTitle class="flex items-center justify-center gap-2 text-2xl text-white">
            Select Your Package
          </CardTitle>
          <CardDescription class="text-gray-300">Choose your preferred package and date</CardDescription>
        </CardHeader>
        <CardContent class="space-y-6 p-8">
          <!-- Package Selection -->
          <div class="space-y-4 mb-8">
            <Label class="text-white text-lg">Select Package *</Label>
            <div class="grid md:grid-cols-2 gap-4">
              <div 
                :class="`cursor-pointer rounded-lg p-4 border-2 transition-all ${
                  formData.selectedPackage === 'vip' 
                    ? 'bg-amber-400/20 border-amber-400' 
                    : 'bg-gray-800 border-gray-600 hover:border-amber-400/50'
                }`"
                @click="selectPackage('vip')"
              >
                <h3 class="text-lg font-semibold text-amber-400 mb-2">King Tut Royal VIP</h3>
                <p class="text-white text-2xl font-bold">€2,900</p>
                <p class="text-gray-300 text-sm">5 Days / 4 Nights</p>
                <p class="text-gray-300 text-sm">per person</p>
              </div>
              <div 
                :class="`cursor-pointer rounded-lg p-4 border-2 transition-all ${
                  formData.selectedPackage === 'oneday' 
                    ? 'bg-amber-400/20 border-amber-400' 
                    : 'bg-gray-800 border-gray-600 hover:border-amber-400/50'
                }`"
                @click="selectPackage('oneday')"
              >
                <h3 class="text-lg font-semibold text-white mb-2">King Tut VIP One Day</h3>
                <p class="text-white text-2xl font-bold">€900</p>
                <p class="text-gray-300 text-sm">Full Day Experience</p>
                <p class="text-gray-300 text-sm">per person</p>
              </div>
            </div>
          </div>
          
          <form @submit.prevent="handleSubmit" class="space-y-6">
            <div class="grid md:grid-cols-2 gap-6">
              <div class="space-y-2">
                <Label for="name" class="text-white">Full Name *</Label>
                <Input
                  id="name"
                  v-model="formData.name"
                  type="text"
                  required
                  class="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                />
              </div>
              
              <div class="space-y-2">
                <Label for="email" class="text-white">Email *</Label>
                <Input
                  id="email"
                  v-model="formData.email"
                  type="email"
                  required
                  class="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                />
              </div>
            </div>

            <div class="grid md:grid-cols-2 gap-6">
              <div class="space-y-2">
                <Label for="phone" class="text-white">Phone *</Label>
                <VueTelInput
                  id="phone"
                  v-model="formData.phone"
                  mode="international"
                  :inputOptions="{ placeholder: 'Enter your phone number' }"
                  class="h-12 bg-gray-800 border-gray-600 text-white focus:border-amber-400"
                />
              </div>

              <div class="space-y-2">
                <Label for="participants" class="text-white">Number of Guests *</Label>
                <select
                  v-model="formData.participants"
                  class="h-12 w-full bg-gray-800 border border-gray-600 text-white rounded-md px-3 focus:border-amber-400 focus:outline-none"
                  style="-webkit-appearance: none; -moz-appearance: none; appearance: none; padding-right: 32px;"
                >
                  <option value="" disabled selected>Select number of guests</option>
                  <template v-if="formData.selectedPackage === 'oneday'">
                    <option value="4">4 Guests</option>
                    <option value="5">5 Guests</option>
                    <option value="6">6 Guests</option>
                  </template>
                  
                  <template v-if="formData.selectedPackage === 'vip'">
                    <option value="1">1 Guest</option>
                    <option value="2">2 Guests</option>
                    <option value="3">3 Guests</option>
                    <option value="4">4 Guests</option>
                    <option value="5">5 Guests</option>
                    <option value="6">6 Guests</option>
                  </template>
                </select>
              </div>
            </div>

            <div class="space-y-2">
              <Label class="text-white">Select Date *</Label>
              <div v-if="formData.selectedPackage === 'oneday'" class="relative">
                <LuxuryDatePicker
                  v-model="selectedOneDayDate"
                  placeholder="Choose your exclusive day"
                  :min-date="new Date()"
                  class="w-full"
                />
              </div>
              <div v-else>
                <select
                  v-model="formData.selectedWeek"
                  required
                  class="h-12 w-full bg-gray-800 border border-gray-600 text-white rounded-md px-3 focus:border-amber-400 focus:outline-none"
                >
                  <option value="">{{ loading ? "Loading dates..." : "Choose your Thursday" }}</option>
                  <template v-for="week in availableWeeks" :key="week.id">
                    <template v-if="new Date(week.week_start_date) >= new Date()">
                      <option 
                        :value="week.week_start_date"
                        :class="{
                          'text-green-400': getAvailableSlots(week) > 25,
                          'text-yellow-400': getAvailableSlots(week) > 12 && getAvailableSlots(week) <= 25,
                          'text-orange-400': getAvailableSlots(week) <= 12
                        }"
                      >
                        {{ getThursdayDate(week.week_start_date) }} - {{ getAvailableSlots(week) }} slots available
                      </option>
                    </template>
                  </template>
                </select>
              </div>
            </div>

            <div class="space-y-2">
              <Label for="requests" class="text-white">Special requests</Label>
              <textarea
                id="requests"
                v-model="formData.specialRequests"
                rows="4"
                class="w-full p-3 bg-gray-800 border border-gray-600 rounded-md text-white focus:border-amber-400 focus:outline-none"
                placeholder="Any special requests or requirements..."
              />
            </div>

            <div class="mt-8 text-center">
              <p class="text-primary text-2xl font-bold">
                Total Price: €{{ calculateTotalPrice(formData.selectedPackage, parseInt(formData.participants)).toLocaleString() }}
              </p>
            </div>

            <Button
              type="submit"
              :disabled="!isFormValid || submitting"
              class="w-full h-14 text-lg bg-gradient-to-r from-amber-400 to-amber-600 text-black hover:from-amber-500 hover:to-amber-700 font-semibold"
            >
              <MessageCircle class="mr-2 h-5 w-5" />
              {{ submitting ? 'Processing...' : 'Secure Your Booking' }}
            </Button>
          </form>
        </CardContent>
      </Card>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted, computed, watch } from 'vue'
import { format } from 'date-fns'
import { MessageCircle } from 'lucide-vue-next'
import { supabase } from '@/lib/supabase'
import Card from '@/components/ui/card.vue'
import CardHeader from '@/components/ui/card-header.vue'
import CardTitle from '@/components/ui/card-title.vue'
import CardDescription from '@/components/ui/card-description.vue'
import CardContent from '@/components/ui/card-content.vue'
import Button from '@/components/ui/button.vue'
import Input from '@/components/ui/input.vue'
import Label from '@/components/ui/label.vue'
import LuxuryDatePicker from '@/components/LuxuryDatePicker.vue'
import { VueTelInput } from 'vue-tel-input'
import 'vue-tel-input/vue-tel-input.css'

interface WeeklyBooking {
  id: number
  week_start_date: string
  booking_count: number
}

const MAX_CAPACITY = 50

// Reactive form data - simplified structure
const formData = reactive({
  name: '',
  phone: '',
  email: '',
  selectedWeek: '',
  participants: '1',
  selectedPackage: 'vip',
  specialRequests: '',
  oneDayDate: '' // Store as string directly for date input
})

// Separate reactive for the luxury date picker
const selectedOneDayDate = ref<Date | null>(null)

// State
const availableWeeks = ref<WeeklyBooking[]>([])
const loading = ref(true)
const submitting = ref(false)
let channel: any = null

// Watch for date picker changes
watch(selectedOneDayDate, (newDate) => {
  if (newDate) {
    formData.oneDayDate = format(newDate, 'yyyy-MM-dd')
  } else {
    formData.oneDayDate = ''
  }
})

// Computed for form validation
const isFormValid = computed(() => {
  const hasName = formData.name && formData.name.trim().length > 0
  const hasEmail = formData.email && formData.email.trim().length > 0
  
  if (!hasName || !hasEmail) return false
  
  if (formData.selectedPackage === 'vip') {
    return formData.selectedWeek && formData.selectedWeek.length > 0
  }
  
  if (formData.selectedPackage === 'oneday') {
    return selectedOneDayDate.value !== null
  }
  
  return false
})

// Methods
const fetchAvailableWeeks = async () => {
  try {
    const { data, error } = await supabase.functions.invoke('get-weekly-bookings')
    if (error) throw error
    
    // Filter weeks that have available slots (less than MAX_CAPACITY bookings)
    const available = data.data.filter((week: WeeklyBooking) => week.booking_count < MAX_CAPACITY)
    availableWeeks.value = available
  } catch (error) {
    console.error('Error fetching available weeks:', error)
  } finally {
    loading.value = false
  }
}

const getThursdayDate = (weekStartDate: string) => {
  const selectedDate = new Date(weekStartDate)
  return format(selectedDate, 'EEEE dd, MMMM yyyy')
}

const getAvailableSlots = (weekData: WeeklyBooking) => {
  return MAX_CAPACITY - weekData.booking_count
}

const calculateTotalPrice = (packageType: string, guests: number) => {
  const pricePerPerson = packageType === 'vip' ? 2900 : 900
  return pricePerPerson * guests
}

const selectPackage = (packageType: 'vip' | 'oneday') => {
  formData.selectedPackage = packageType
  if (packageType === 'oneday') {
    formData.participants = '4' // Set minimum for one day package
  }
}

const handleSubmit = async () => {
  if (!formData.name.trim()) {
    alert('Please enter your full name.')
    return
  }

  if (!formData.phone.trim()) {
    alert('Please enter your phone number.')
    return
  }

  if (!formData.participants || parseInt(formData.participants) <= 0) {
    alert('Please enter the number of guests.')
    return
  }

  if (formData.selectedPackage === 'vip' && !formData.selectedWeek) {
    alert('Please select a week for the Royal VIP package.')
    return
  }

  if (formData.selectedPackage === 'oneday' && !formData.oneDayDate) {
    alert('Please select a date for the One Day package.')
    return
  }

  submitting.value = true

  let bookingDateDisplay = ''
  let newBookingCount = 0
  let remainingSlots = 0

  try {
    if (formData.selectedPackage === 'vip') {
      // Check if enough slots are available
      const selectedWeekData = availableWeeks.value.find(w => w.week_start_date === formData.selectedWeek)
      if (!selectedWeekData) {
        throw new Error('Selected week data not found')
      }
      
      const availableSlots = getAvailableSlots(selectedWeekData)
      const requestedParticipants = parseInt(formData.participants)
      
      if (requestedParticipants > availableSlots) {
        alert(`Not enough slots available. Requested: ${requestedParticipants}, Available: ${availableSlots}`)
        submitting.value = false
        return
      }

      // Book the slot for VIP package
      const { data, error } = await supabase.functions.invoke('book-weekly-slot', {
        body: { weekStartDate: formData.selectedWeek, participants: requestedParticipants }
      })

      if (error) throw error
      if (!data.success) throw new Error(data.message)

      newBookingCount = data.newCount
      bookingDateDisplay = getThursdayDate(formData.selectedWeek)
      remainingSlots = MAX_CAPACITY - newBookingCount
    } else if (formData.selectedPackage === 'oneday' && formData.oneDayDate) {
      // For one-day package, no slot booking needed on backend for now
      // Just format the date for display
      bookingDateDisplay = format(new Date(formData.oneDayDate), 'EEEE dd, MMMM yyyy') // e.g., 'Monday 25, October 2024'
      newBookingCount = 0 // Not applicable for one-day
      remainingSlots = 0 // Not applicable for one-day
    }

    const totalPrice = calculateTotalPrice(formData.selectedPackage, parseInt(formData.participants))
    const packageName = formData.selectedPackage === 'vip' ? 'King Tut Royal VIP (5 Days / 4 Nights)' : 'King Tut VIP One Day'

    const message = `
🎁 *${packageName}*

📋 *Booking Details:*
${formData.selectedPackage === 'vip' ? `🎫 Booking number: ${newBookingCount}` : ''}
👤 Name: ${formData.name}
📱 Phone: ${formData.phone}
📧 Email: ${formData.email}
👥 Guests: ${formData.participants}
📅 Booking Date: ${bookingDateDisplay}
€ Total Price: €${totalPrice.toLocaleString()}
${formData.selectedPackage === 'vip' ? `🎟️ Remaining Slots: ${remainingSlots}` : ''}
${formData.specialRequests ? `📝 Special Requests: ${formData.specialRequests}` : ''}
`

    const whatsappUrl = `https://api.whatsapp.com/send?phone=971585923054&text=${encodeURIComponent(message)}`
    window.open(whatsappUrl, '_blank')

    // Refresh available weeks (only relevant for VIP package)
    if (formData.selectedPackage === 'vip') {
      await fetchAvailableWeeks()
    }

    // Reset form
    Object.assign(formData, {
      name: '',
      phone: '',
      email: '',
      selectedWeek: '',
      participants: '1',
      selectedPackage: 'vip',
      specialRequests: '',
      oneDayDate: ''
    })
    selectedOneDayDate.value = null
  } catch (error) {
    console.error('Booking error:', error)
    alert('Booking failed. Please try again.')
  } finally {
    submitting.value = false
  }
}

// Lifecycle
onMounted(async () => {
  await fetchAvailableWeeks()
  
  // Subscribe to realtime changes
  channel = supabase
    .channel('weekly_bookings_changes')
    .on('postgres_changes', 
      { event: '*', schema: 'public', table: 'weekly_bookings' },
      () => {
        fetchAvailableWeeks()
      }
    )
    .subscribe()
})

onUnmounted(() => {
  if (channel) {
    supabase.removeChannel(channel)
  }
})
</script>

<style>
.vue-tel-input {
  background-color: #1f2937 !important; /* bg-gray-800 */
  border-color: #4b5563 !important; /* border-gray-600 */
  color: #ffffff !important; /* text-white */
  border-radius: 0.375rem !important; /* rounded-md */
}

.vue-tel-input:focus-within {
  box-shadow: 0 0 0 2px rgba(251, 191, 36, 0.5) !important; /* focus:border-amber-400 with shadow */
  border-color: #fbbf24 !important; /* focus:border-amber-400 */
}

.vue-tel-input .vti__dropdown {
  background-color: #1f2937 !important; /* bg-gray-800 */
  border-color: #4b5563 !important; /* border-gray-600 */
  color: #ffffff !important; /* text-white */
}

.vue-tel-input .vti__dropdown.open {
  background-color: #1f2937 !important; /* bg-gray-800 */
  border-color: #4b5563 !important; /* border-gray-600 */
}

.vue-tel-input .vti__dropdown-item {
  background-color: #1f2937 !important; /* bg-gray-800 */
  color: #ffffff !important; /* text-white */
}

.vue-tel-input .vti__dropdown-item.highlighted {
  background-color: #2d3748 !important; /* A slightly lighter gray for hover/focus */
}

.vue-tel-input .vti__input {
  background-color: #1f2937 !important; /* bg-gray-800 */
  border-color: #4b5563 !important; /* border-gray-600 */
  color: #ffffff !important; /* text-white */
  border-radius: 0.375rem !important; /* rounded-md */
}
</style>
