// src/components/sections/MediaSliderSection.vue
<template>
  <section class="py-12 bg-light-yellow">
    <div class="container mx-auto px-4">
      <div class="text-center mb-8">
        <h4 class="text-lg text-brownish max-w-3xl mx-auto font-bold leading-relaxed">
          Immerse yourself in luxury Egyptian experiences
        </h4>
      </div>

      <div class="relative max-w-6xl mx-auto">
        <SplideCarousel
          :slides="splideSlides"
          :options="splideOptions"
          aria-label="Luxury Egyptian Experiences Carousel"
        />
      </div>
    </div>
  </section>

  <!-- Modal -->
  <div
    v-if="isModalOpen"
    class="fixed inset-0 z-50 flex items-center justify-center bg-background/90 p-4"
  >
    <div class="relative max-w-7xl max-h-full w-full h-full flex items-center justify-center">
      <img
        :src="mediaItems[modalImageIndex].src"
        :alt="mediaItems[modalImageIndex].title"
        class="max-w-full max-h-full object-contain rounded-lg"
        width="853"
        height="480"
      />

      <Button
        @click="closeModal"
        variant="ghost"
        size="icon"
        class="absolute top-4 right-4 bg-card/50 hover:bg-card/70 text-foreground border-0 h-12 w-12 rounded-full"
      >
        <X class="h-6 w-6" />
      </Button>

      <Button
        @click="prevModalImage"
        variant="ghost"
        size="icon"
        class="absolute left-4 top-1/2 -translate-y-1/2 bg-card/50 hover:bg-card/70 text-foreground border-0 h-12 w-12 rounded-full"
      >
        <ChevronLeft class="h-6 w-6" />
      </Button>

      <Button
        @click="nextModalImage"
        variant="ghost"
        size="icon"
        class="absolute right-4 top-1/2 -translate-y-1/2 bg-card/50 hover:bg-card/70 text-foreground border-0 h-12 w-12 rounded-full"
      >
        <ChevronRight class="h-6 w-6" />
      </Button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import { ChevronLeft, ChevronRight, X, Maximize2 } from 'lucide-vue-next';
import Button from '../ui/button.vue';
import SplideCarousel from '../SplideCarousel.vue';

const isModalOpen = ref(false);
const modalImageIndex = ref(0);

const mediaItems = [
  {
    id: 0,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-dawn.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-dawn-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-dawn-853w.webp",
    title: "Pyramid in Dawn time",
    description: "Unforgettable pyramid experience"
  },
  {
    id: 1,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/bus.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/bus-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/bus-853w.webp",
    title: "Perfume Experience",
    description: "Unforgettable perfume package"
  },
  {
    id: 2,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-light.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-light-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-light-853w.webp",
    title: "Pyramid",
    description: "Unforgettable pyramid experience"
  },
  {
    id: 3,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/m-out.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/m-out-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/m-out-853w.webp",
    title: "Museum of the Ancient World",
    description: "Museum from outer side"
  },
  {
    id: 4,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/tut.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/tut-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/tut-853w.webp",
    title: "King Tut Monuments",
    description: "Unforgettable King Tut experience"
  },
  {
    id: 5,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-camel.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-camel-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/pyramid-camel-853w.webp",
    title: "Pyramid in Camel time",
    description: "Unforgettable pyramid experience"
  },
  {
    id: 6,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/CROHA%20Exterior%20ByDay.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/CROHA%20Exterior%20ByDay-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/CROHA%20Exterior%20ByDay-853w.webp",
    title: "CROHA",
    description: "Unforgettable CROHA experience"
  },
  {
    id: 7,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/ICSemiramis%20lobby.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/ICSemiramis%20lobby-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/ICSemiramis%20lobby-853w.webp",
    title: "ICSemiramis",
    description: "Unforgettable ICSemiramis experience"
  },
  {
    id: 8,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/Intercontinental%20rooms9166.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/Intercontinental%20rooms9166-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/Intercontinental%20rooms9166-853w.webp",
    title: "ICSemiramis",
    description: "ICSemiramis rooms experience"
  },
  {
    id: 9,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/Intercontinental%20rooms9196.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/Intercontinental%20rooms9196-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/Intercontinental%20rooms9196-853w.webp",
    title: "ICSemiramis",
    description: "ICSemiramis rooms experience"
  },
  {
    id: 10,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/museum-out.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/museum-out-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/museum-out-853w.webp",
    title: "Museum",
    description: "Unforgettable museum experience"
  },
  {
    id: 11,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/museum-in.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/museum-in-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/museum-in-853w.webp",
    title: "Museum",
    description: "Unforgettable museum experience"
  },
  {
    id: 12,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/car.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/car-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/car-853w.webp",
    title: "Car",
    description: "Unforgettable museum experience"
  },
  {
    id: 13,
    src: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/grave.webp",
    src_412w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/grave-412w.webp",
    src_853w: "https://mhwjdkzpnhzmduolfgmy.supabase.co/storage/v1/object/public/images/homepage/media-slider/grave-853w.webp",
    title: "King Tut Grave",
    description: "Unforgettable King Tut Grave experience"
  }
];

const splideSlides = computed(() => mediaItems.map(item => ({
  type: 'image',
  src: item.src,
  alt: item.title,
  id: item.id
})));

const splideOptions = {
  rewind: true,
  autoplay: true,
  interval: 4000,
  pauseOnHover: true,
  lazyLoad: true,
  perPage: 1,
  height: '500px',
  breakpoints: {
    640: {
      height: '250px',
    },
    768: {
      height: '350px',
    },
    1024: {
      height: '450px',
    },
  },
};

function openModal(index: number) {
  if (!isModalOpen.value) {
    isModalOpen.value = true;
    modalImageIndex.value = index;
  }
}
function closeModal() {
  isModalOpen.value = false;
}

function nextModalImage() {
  if (mediaItems.length > 1) {
    modalImageIndex.value = (modalImageIndex.value + 1) % mediaItems.length;
  }
}

function prevModalImage() {
  if (mediaItems.length > 1) {
    modalImageIndex.value = (modalImageIndex.value - 1 + mediaItems.length) % mediaItems.length;
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (!isModalOpen.value) return;
  if (e.key === 'Escape') {
    isModalOpen.value = false;
  } else if (e.key === 'ArrowLeft') {
    prevModalImage();
  } else if (e.key === 'ArrowRight') {
    nextModalImage();
  }
}

onMounted(() => {
  window.addEventListener('keydown', handleKeydown);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeydown);
});

watch(isModalOpen, (newValue) => {
  if (newValue) {
    document.body.style.overflow = 'hidden';
  } else {
    document.body.style.overflow = '';
  }
});

</script>

// src/components/MediaSliderSection.tsx
import React, { useState, useEffect } from 'react';
import { ChevronLeft, ChevronRight, X, Maximize2 } from 'lucide-react';
import { Button } from './ui/button';

const MediaSliderSection: React.FC = () => {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [modalImageIndex, setModalImageIndex] = useState(0);
  
  const mediaItems = [
    {
      id: 0,
      src: "/images/vip.jpeg",
      title: "VIP Experience",
      description: "Exclusive access and personalized service"
    },
    {
      id: 1,
      src: "/images/luxury.jpeg",
      title: "Luxury Travel",
      description: "Unforgettable journeys with unparalleled comfort"
    },
    {
      id: 2,
      src: "/images/chills.jpeg",
      title: "Luxury Travel",
      description: "Unforgettable journeys with unparalleled comfort"
    },
    {
      id: 3,
      src: "https://d64gsuwffb70l.cloudfront.net/68b1c96bae343289de113d06_1756563690287_c291debe.jpeg",
      title: "Core Services",
      description: "Luxury accommodations and premium experiences"
    },
    {
      id: 4,
      src: "https://d64gsuwffb70l.cloudfront.net/68b1c96bae343289de113d06_1756563690822_f6641d5a.jpeg",
      title: "Digital Experience",
      description: "AR-enhanced tours and mobile concierge"
    },
    {
      id: 5,
      src: "https://d64gsuwffb70l.cloudfront.net/68b1c96bae343289de113d06_1756569116369_624ffd5b.jpeg",
      title: "Royal Dinner on the Nile",
      description: "Exclusive dining experiences with ancient Egyptian ambiance"
    },
    {
      id: 6,
      src: "https://d64gsuwffb70l.cloudfront.net/68b1c96bae343289de113d06_1756569118036_1d19752f.jpeg",
      title: "King Tut Royal Collection",
      description: "Limited edition luxury items inspired by pharaonic treasures"
    },
    {
      id: 7,
      src: "https://d64gsuwffb70l.cloudfront.net/68b1c96bae343289de113d06_1756569118786_e66e165b.jpeg",
      title: "VIP Experience Package",
      description: "Premium access and personalized Egyptian adventure"
    }
  ];

  // Auto-switch functionality
  useEffect(() => {
    if (!isModalOpen) {
      const interval = setInterval(() => {
        setCurrentSlide((prev) => (prev + 1) % mediaItems.length);
      }, 4000); // Switch every 4 seconds

      return () => clearInterval(interval);
    }
  }, [mediaItems.length, isModalOpen]);

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev + 1) % mediaItems.length);
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev - 1 + mediaItems.length) % mediaItems.length);
  };

  const goToSlide = (index: number) => {
    setCurrentSlide(index);
  };

  const openModal = (index: number) => {
    setModalImageIndex(index);
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
  };

  const nextModalImage = () => {
    setModalImageIndex((prev) => (prev + 1) % mediaItems.length);
  };

  const prevModalImage = () => {
    setModalImageIndex((prev) => (prev - 1 + mediaItems.length) % mediaItems.length);
  };

  return (
    <>
      <section className="py-12 bg-gray-950">
        <div className="container mx-auto px-4">
          <div className="text-center mb-8">
            <h4 className="text-lg text-gray-300 max-w-3xl mx-auto font-light leading-relaxed">
              Immerse yourself in luxury Egyptian experiences
            </h4>
          </div>

          <div className="relative max-w-6xl mx-auto">
            <div className="relative h-64 sm:h-80 md:h-96 lg:h-[500px] xl:h-[600px] overflow-hidden rounded-2xl group cursor-pointer"
                 onClick={() => openModal(currentSlide)}>
              <img
                src={mediaItems[currentSlide].src}
                alt={mediaItems[currentSlide].title}
                className="w-full h-full object-contain transition-all duration-500"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"></div>
              
              {/* Maximize button */}
              <div className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                <Button
                  variant="ghost"
                  size="icon"
                  className="bg-black/50 hover:bg-black/70 text-white border-0 h-10 w-10 rounded-full"
                >
                  <Maximize2 className="h-5 w-5" />
                </Button>
              </div>
            </div>

            <Button
              onClick={prevSlide}
              variant="ghost"
              size="icon"
              className="absolute left-4 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70 text-white border-0 h-12 w-12 rounded-full"
            >
              <ChevronLeft className="h-6 w-6" />
            </Button>

            <Button
              onClick={nextSlide}
              variant="ghost"
              size="icon"
              className="absolute right-4 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70 text-white border-0 h-12 w-12 rounded-full"
            >
              <ChevronRight className="h-6 w-6" />
            </Button>

            <div className="flex justify-center mt-8 space-x-3">
              {mediaItems.map((_, index) => (
                <button
                  key={index}
                  onClick={() => goToSlide(index)}
                  className={`w-3 h-3 rounded-full transition-all duration-300 ${
                    index === currentSlide 
                      ? 'bg-yellow-400 scale-125' 
                      : 'bg-gray-600 hover:bg-gray-400'
                  }`}
                />
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4">
          <div className="relative max-w-7xl max-h-full w-full h-full flex items-center justify-center">
            <img
              src={mediaItems[modalImageIndex].src}
              alt={mediaItems[modalImageIndex].title}
              className="max-w-full max-h-full object-contain rounded-lg"
            />
            
            <Button
              onClick={closeModal}
              variant="ghost"
              size="icon"
              className="absolute top-4 right-4 bg-black/50 hover:bg-black/70 text-white border-0 h-12 w-12 rounded-full"
            >
              <X className="h-6 w-6" />
            </Button>

            <Button
              onClick={prevModalImage}
              variant="ghost"
              size="icon"
              className="absolute left-4 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70 text-white border-0 h-12 w-12 rounded-full"
            >
              <ChevronLeft className="h-6 w-6" />
            </Button>

            <Button
              onClick={nextModalImage}
              variant="ghost"
              size="icon"
              className="absolute right-4 top-1/2 -translate-y-1/2 bg-black/50 hover:bg-black/70 text-white border-0 h-12 w-12 rounded-full"
            >
              <ChevronRight className="h-6 w-6" />
            </Button>
          </div>
        </div>
      )}
    </>
  );
};

export default MediaSliderSection;
