// src/components/PackageCard.tsx
import React from 'react';

interface PackageCardProps {
  title: string;
  price: string;
  duration: string;
  image: string;
  highlights: string[];
  isPopular?: boolean;
  onBookNow: () => void;
}

const PackageCard: React.FC<PackageCardProps> = ({
  title,
  price,
  duration,
  image,
  highlights,
  isPopular = false,
  onBookNow
}) => {
  return (
    <div className={`bg-gray-900 border border-gray-800 hover:border-yellow-400/50 transition-all duration-300 group ${isPopular ? 'border-yellow-400' : ''}`}>
      {isPopular && (
        <div className="bg-yellow-400 text-black px-4 py-1 text-sm font-medium text-center">
          MOST POPULAR
        </div>
      )}
      
      <div className="relative h-80 overflow-hidden">
        <img 
          src={image} 
          alt={title}
          className="w-full h-full object-contain group-hover:scale-105 transition-transform duration-500"
        />
      </div>

      <div className="p-8">
        <div className="text-center mb-8">
          <div className="w-16 h-16 bg-yellow-400 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-black" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12 2L15.09 8.26L22 9L17 14L18.18 21L12 17.77L5.82 21L7 14L2 9L8.91 8.26L12 2Z"/>
            </svg>
          </div>
          <h3 className="text-3xl font-semibold text-white mb-3">{title}</h3>
          <p className="text-gray-300 text-lg tracking-wide font-medium">{duration}</p>
        </div>

        <div className="text-center mb-8">
          <div className="text-4xl font-semibold text-yellow-400 mb-2">{price}</div>
          <div className="text-gray-300 text-base font-medium">per person</div>
        </div>

        <div className="mb-8">
          <ul className="space-y-4">
            {highlights.slice(0, 4).map((highlight, index) => (
              <li key={index} className="flex items-start text-base">
                <span className="text-yellow-400 mr-3 mt-1 text-lg">•</span>
                <span className="text-gray-200 font-medium leading-relaxed">{highlight}</span>
              </li>
            ))}
          </ul>
        </div>

        <button 
          onClick={onBookNow}
          className="w-full bg-yellow-400 hover:bg-yellow-300 text-black py-4 font-semibold tracking-wider transition-all duration-300 uppercase text-base"
        >
          Book Now
        </button>
      </div>
  );
};

export default PackageCard;

// src/components/PackageCard.vue
<template>
  <div :class="['bg-gray-900 border group hover:border-yellow-400/50 transition-all duration-300 rounded-lg flex flex-col text-center overflow-hidden', isPopular ? 'border-yellow-400' : 'border-gray-800']">
    <div class="relative w-full h-48 overflow-hidden bg-gray-600">
      <img
        :src="image"
        :alt="title"
        class="w-full h-full object-contain group-hover:scale-105 transition-transform duration-500"
      />
      <div v-if="isPopular" class="absolute top-2 right-2 bg-yellow-400 text-black px-3 py-1 text-xs font-medium rounded-full">
        Popular
      </div>
    </div>

    <div class="p-6 flex flex-col flex-grow">
      <div class="flex items-center justify-center mb-3">
        <div class="w-8 h-8 bg-yellow-400 rounded-full flex items-center justify-center mr-2">
          <component :is="LucideIcon" :size="20" class="text-black" />
        </div>
        <h3 class="text-xl font-semibold text-white">{{ title }}</h3>
      </div>
      <p class="text-gray-300 text-sm tracking-wide font-medium mb-2">{{ duration }}</p>
      <div class="text-2xl font-semibold text-yellow-400 mb-4">{{ price }} <span class="text-gray-300 text-sm font-medium">per person</span></div>

      <div class="mb-6 flex-grow">
        <ul class="space-y-2 text-left">
          <li v-for="(highlight, index) in highlights.slice(0, 3)" :key="index" class="flex items-start text-sm">
            <span class="text-yellow-400 mr-2 text-base">•</span>
            <span class="text-gray-200 font-medium leading-tight">{{ highlight }}</span>
          </li>
        </ul>
      </div>

      <div class="mt-auto space-y-3">
        <button
          @click="onViewDetailsClick"
          class="w-full bg-yellow-400 hover:bg-yellow-300 text-black py-3 font-semibold tracking-wider transition-all duration-300 uppercase text-sm"
        >
          View Details
        </button>
        <button
          @click="onBookNowClick"
          class="w-full border border-yellow-400 text-yellow-400 hover:bg-yellow-400 hover:text-black py-3 font-semibold tracking-wider transition-all duration-300 uppercase text-sm"
        >
          Book Now
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps, computed } from 'vue';
import * as icons from "lucide-vue-next";

interface PackageCardProps {
  title: string;
  price: string;
  duration: string;
  image: string;
  highlights: string[];
  isPopular?: boolean;
  onBookNowClick: () => void;
  onViewDetailsClick: () => void;
  icon: string;
}

const props = withDefaults(defineProps<PackageCardProps>(), {
  isPopular: false,
});

const LucideIcon = computed(() => icons[props.icon]);
</script>
