// src/components/PackageDetailsModal.tsx
import React from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "./ui/dialog";
import { Button } from "./ui/button";
import { X, Star, Gift, Clock, Users, MapPin } from "lucide-react";

interface PackageDetailsModalProps {
  isOpen: boolean;
  onClose: () => void;
  packageData: {
    id: number;
    title: string;
    price: string;
    duration: string;
    image: string;
    description: string;
    features: string[];
    highlights: string[];
    included: string[];
    itinerary: { day: string; activities: string[] }[];
  } | null;
  onBookNow: () => void;
}

const PackageDetailsModal: React.FC<PackageDetailsModalProps> = ({
  isOpen,
  onClose,
  packageData,
  onBookNow
}) => {
  if (!packageData) return null;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="bg-gray-900 border-gray-800 text-white max-w-4xl max-h-[90vh] overflow-y-auto p-3 sm:p-6">
        <DialogHeader>
          <DialogTitle className="text-xl sm:text-2xl lg:text-3xl font-semibold text-white mb-3 sm:mb-4">
            {packageData.title}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 sm:space-y-6 lg:space-y-8">
          <div className="relative h-48 sm:h-56 lg:h-64 overflow-hidden rounded-lg">
            <img 
              src={packageData.image} 
              alt={packageData.title}
              className="w-full h-full object-contain bg-gray-800"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6 lg:gap-8">
            <div>
              <h3 className="text-base sm:text-lg lg:text-xl font-semibold text-yellow-400 mb-2 sm:mb-3 flex items-center">
                <Gift className="h-4 w-4 sm:h-5 sm:w-5 mr-2" />
                Package Features
              </h3>
              <ul className="space-y-1 sm:space-y-2">
                {packageData.features.map((feature, index) => (
                  <li key={index} className="text-gray-300 flex items-start text-xs sm:text-sm lg:text-base">
                    <span className="text-yellow-400 mr-2 text-sm sm:text-base">•</span>
                    {feature}
                  </li>
                ))}
              </ul>
            </div>

            <div>
              <h3 className="text-base sm:text-lg lg:text-xl font-semibold text-yellow-400 mb-2 sm:mb-3 flex items-center">
                <Star className="h-4 w-4 sm:h-5 sm:w-5 mr-2" />
                What's Included
              </h3>
              <ul className="space-y-1 sm:space-y-2">
                {packageData.included.map((item, index) => (
                  <li key={index} className="text-gray-300 flex items-start text-xs sm:text-sm lg:text-base">
                    <span className="text-yellow-400 mr-2 text-sm sm:text-base">•</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div className="border-t border-gray-800 pt-4 sm:pt-6 lg:pt-8">
            <div className="flex flex-col sm:flex-row justify-between items-center gap-4 sm:gap-0">
              <div className="text-center sm:text-left">
                <div className="text-2xl sm:text-3xl lg:text-4xl font-bold text-yellow-400">{packageData.price}</div>
                <div className="text-gray-400 text-sm sm:text-base font-medium mt-1">{packageData.duration}</div>
              </div>
              <Button 
                onClick={() => {
                  onClose();
                  setTimeout(() => onBookNow(), 300);
                }}
                className="bg-yellow-400 hover:bg-yellow-300 text-black font-semibold px-4 sm:px-6 py-2 sm:py-3 text-sm sm:text-base w-full sm:w-auto"
              >
                Book This Experience
              </Button>

            </div>
          </div>
        </div>
        </DialogContent>
      </Dialog>
    );
  };
  
  export default PackageDetailsModal;

// src/components/PackageDetailsModal.vue
<template>
  <div v-if="isOpen" class="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50">
    <div class="bg-gray-900 text-white p-8 rounded-lg max-w-3xl w-full max-h-[90vh] overflow-y-auto relative">
      <button @click="closeModal" class="absolute top-4 right-4 text-gray-400 hover:text-white text-2xl">&times;</button>
      <h2 class="text-4xl font-bold text-yellow-400 mb-6 text-center">{{ package.title }}</h2>

      <div v-if="package.details.images && package.details.images.length > 0" class="mb-8">
        <h3 class="text-2xl font-semibold text-white mb-3">Gallery</h3>
        <div class="relative w-full h-80 overflow-hidden rounded-lg mb-4 bg-gray-600">
          <img :src="package.details.images[currentImageIndex]" alt="Package Image" class="w-full h-full object-contain transition-opacity duration-300" />
          <button @click="prevImage" class="absolute left-0 top-1/2 -translate-y-1/2 bg-black bg-opacity-50 text-white p-2 rounded-full ml-2">&lt;</button>
          <button @click="nextImage" class="absolute right-0 top-1/2 -translate-y-1/2 bg-black bg-opacity-50 text-white p-2 rounded-full mr-2">&gt;</button>
        </div>
        <div class="flex justify-center space-x-2">
          <img v-for="(img, idx) in package.details.images" :key="idx" :src="img" @click="setCurrentImage(idx)" :class="{'border-2 border-yellow-400': idx === currentImageIndex}" class="w-20 h-16 object-cover rounded-lg cursor-pointer" />
        </div>
      </div>

      <div class="mb-8">
        <h3 class="text-2xl font-semibold text-white mb-3">Overview</h3>
        <p class="text-gray-300 text-lg leading-relaxed whitespace-pre-line">{{ package.details.overview }}</p>
      </div>

      <div class="mb-8">
        <h3 class="text-2xl font-semibold text-white mb-3">Accommodation</h3>
        <p class="text-gray-300 text-lg leading-relaxed whitespace-pre-line">{{ package.details.accommodation }}</p>
      </div>

      <div class="mb-8">
        <h3 class="text-2xl font-semibold text-white mb-4">Itinerary Highlights</h3>
        <div v-for="(item, index) in package.details.itinerary" :key="index" class="mb-6 last:mb-0">
          <h4 class="text-xl font-semibold text-yellow-400 mb-2">{{ item.day }}</h4>
          <p class="text-gray-300 text-lg leading-relaxed whitespace-pre-line">{{ item.description }}</p>
        </div>
      </div>

      <div class="mb-8">
        <h3 class="text-2xl font-semibold text-white mb-3">Exclusive Benefits</h3>
        <p class="text-gray-300 text-lg leading-relaxed whitespace-pre-line">{{ package.details.benefits }}</p>
      </div>

      <div class="mb-8">
        <h3 class="text-2xl font-semibold text-white mb-3">Booking Information</h3>
        <p class="text-gray-300 text-lg leading-relaxed whitespace-pre-line">{{ package.details.booking }}</p>
      </div>

      <div class="text-center mt-8 space-y-4">
        <button @click="bookNowAndClose" class="w-full bg-yellow-400 hover:bg-yellow-300 text-black py-3 px-8 rounded-lg font-semibold text-lg transition-all duration-300">
          Book Now
        </button>
        <button @click="closeModal" class="w-full border border-yellow-400 text-yellow-400 hover:bg-yellow-400 hover:text-black py-3 px-8 rounded-lg font-semibold text-lg transition-all duration-300">
          Close
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps, defineEmits, ref } from 'vue';
import { smoothScroll } from '../utils/smoothScroll';

const currentImageIndex = ref(0);

const prevImage = () => {
  currentImageIndex.value = (currentImageIndex.value - 1 + props.package.details.images.length) % props.package.details.images.length;
};

const nextImage = () => {
  currentImageIndex.value = (currentImageIndex.value + 1) % props.package.details.images.length;
};

const setCurrentImage = (index: number) => {
  currentImageIndex.value = index;
};

interface PackageDetails {
  overview: string;
  accommodation: string;
  itinerary: { day: string; description: string }[];
  benefits: string;
  booking: string;
  images: string[];
}

interface Package {
  title: string;
  price: string;
  duration: string;
  image: string;
  highlights: string[];
  isPopular?: boolean;
  details: PackageDetails;
}

const props = defineProps({
  isOpen: {
    type: Boolean,
    required: true,
  },
  package: {
    type: Object as () => Package,
    required: true,
  },
});

const emit = defineEmits(['close']);

const closeModal = () => {
  emit('close');
};

const bookNowAndClose = () => {
  closeModal();
  smoothScroll('booking');
};
</script>

<style scoped>
/* Add any specific styles for the modal here if needed */
</style>
